name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
  

env:
  FLUTTER_VERSION: '3.16.x'

jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub get
      - run: flutter analyze --fatal-infos

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .

  build-android && upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip libunwind-dev
      - run: flutter --disable-analytics
      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v3 # upload the app
        with:
          name: sorted-android
          path: build/app/outputs/apk/release/app-release.apk
      

